[package]
name = "check-if-email-exists-serverless"
version = "0.4.0"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = "0.6"
futures = "0.3"
http = "0.1"
lambda_http = "0.1"
lambda_runtime = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
