CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    stripe_customer VARCHAR(255) NOT NULL
);

CREATE TABLE api_tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_token UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    stripe_subscription_item VARCHAR(255) NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    CONSTRAINT fk_user
      FOREIGN KEY(user_id) 
	    REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE api_usage_records (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_token_id INT NOT NULL,
    method VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_api_token
      FOREIGN KEY(api_token_id) 
	    REFERENCES api_tokens(id)
        ON DELETE CASCADE
);
