name: master

on:
  push:
    branches:
      - master

jobs:
  # Deploy the code to Heroku.
  heroku-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: reacher-email-staging
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
