name: master

on:
  push:
    branches:
      - master

jobs:
  # Deploy to serverless, using the `dev` stage.
  serverless-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - run: yarn install
      - name: serverless deploy
        run: yarn serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
